#! /bin/bash

NAME="hunan-culture"
HNC_DIR=/home/dev/workspaces/python-workspace/projects/hunan-culture
VENV_DIR=/home/dev/workspaces/python-workspace/flask-env
SOCK_FILE=/home/dev/workspaces/python-workspace/projects/hunan-culture/sock
TMP_DIR=/tmp/hnc
USER=dev
GROUP=dev
NUM_WORKERS=1

echo "Starting $NAME"

cd $VENV_DIR
source bin/activate

cd $HNC_DIR

export PSYCOGREEN=true
RUN_DIR=$(dirname $SOCK_FILE)
test -d  $RUN_DIR || mkdir -p $RUN_DIR
test -d  $TMP_DIR || mkdir -p $TMP_DIR

exec gunicorn app:application -b 127.0.0.1:8300 -k gevent \
    --name $NAME \
    --workers $NUM_WORKERS \
    --user=$USER --group=$GROUP \
    --log-level=error \
    --error-logfile /home/dev/workspaces/python-workspace/projects/hunan-culture/logs/gunicorn.log \
    --bind=unix:$SOCK_FILE

